### ISSUE TITLE
Installing, licencing, usage

### ISSUE THREAD

**Issue by jgebal** [morten-egan/testdata_ninja#1]
Hi,
I've read your article on [codemonth.dk](http://www.codemonth.dk/code_is_good/dev_qa_prod.assert?condition=codemonth::::13376:Even-more-test-data-generated-using-the-testdata_ninja-plsql-package)
I would be interested in trying the testdata_ninja as a helper library for mock data setup for unit testing using [utPLSQL v3](https://github.com/utPLSQL/utPLSQL)

So few questions:

- [x] what is the license for *testdata_ninja*?
- [x] what other libraries are required ad what is their licensing?
- [x] How do I install it all
- [x] where can I read about how to use it? Is there a user guide?

Thanks
Jacek

**Comment by morten-egan** [comment]
Hi Jacek,License is MIT, and if not updated to that I will do that after work todayTo really be useful you should use it together with random_ninja also written by me, although it is not a requirement. Should also be MIT but I will make sure today after work. Should be an install guide for both libraries in the blog entry on codeMonth. Look for the gist link within the article http://www.codemonth.dk/code_is_good/dev_qa_prod.assert?condition=codemonth::::11370:Updated-random_ninja-and-testdata_ninja-packagesI have not written an actual user guide although the libraries should be pretty much self explanatory if you read through the different blog entries on codemonth website:Random_ninja:http://codemonth.dk/code_is_good/dev_qa_prod.assert?condition=codemonth:::19::Random-data-in-OracleTestdata_ninja:http://codemonth.dk/code_is_good/dev_qa_prod.assert?condition=codemonth:::20:If you need a more detailed explanation or have any additional questions let me know. Thanks,Morten---- On Mon, 19 Jun 2017 03:39:59 +0800  Jacek Gębal<notifications@github.com> wrote ----Hi, I've read your article on codemonth.dk I would be interested in trying the testdata_ninja as a helper library for mock data setup for unit testing using utPLSQL v3 So few questions: -[ ] what is the license for testdata_ninja? -[ ] what other libraries are required ad what is their licensing? -[ ] How do I install it all -[ ] where can I read about how to use it? Is there a user guide? Thanks Jacek  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by morten-egan** [comment]
I will update the readme later tonight with a simple user guide.

**Comment by jgebal** [comment]
Awesome!
Thank you @morten-egan.
I will try to spend some time trying out your test data for data setups using utPLSQL v3.
Looks like you did a piece of amazing work.
I'm truly surprised I didn't find it any sooner.
It seems that combining utPLSQL v3 with tesdata_ninja can give a huge value to unit testing of ORacle databases.

**Comment by morten-egan** [comment]
I'm writing a user guide at the moment. Should be done within this week.

**Comment by morten-egan** [comment]
User guide written: https://github.com/morten-egan/testdata_ninja#user-guide
